spring.application.name=redis-spring-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/redis_spring_lab_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.cache.type=simple

logging.level.org.springframework=INFO
logging.level.br.wesley=DEBUG

